include:
  - board: seeeduino_xiao_ble
    shield: aegir_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: seeeduino_xiao_ble
    shield: aegir_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: raytac_mdbt50q_rx
    shield: aegir_dongle
  - board: raytac_mdbt50q_rx
    shield: settings_reset
