include:
  - board: seeeduino_xiao_ble
    shield: aegir_central_left
  - board: seeeduino_xiao_ble
    shield: aegir_peripheral_left
  - board: seeeduino_xiao_ble
    shield: aegir_peripheral_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: aegir_central_dongle
  - board: raytac_mdbt50q_rx
    shield: aegir_central_dongle
  - board: raytac_mdbt50q_rx
    shield: settings_reset
