include:
  - board: seeeduino_xiao_ble
    shield: aegir_central_left
  - board: seeeduino_xiao_ble
    shield: aegir_peripheral_left
  - board: seeeduino_xiao_ble
    shield: aegir_peripheral_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: aegir_central_dongle dongle_display
    artifact_name: aegir_central_dongle
