manifest:
  remotes:
    # - name: zmkfirmware
    #   url-base: https://github.com/zmkfirmware
    - name: zmkfirmware
      url-base: https://github.com/Genteure
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/battery-reporting
      import: app/west.yml
  self:
    path: config
