manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # - name: zmkfirmware
    #   url-base: https://github.com/Genteure
    - name: rschenk
      url-base: https://github.com/rschenk
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
      # revision: feat/battery-reporting
    - name: zmk-component-raytac-dongle
      remote: rschenk
      revision: main
  self:
    path: config
